name: xmos-ai-tools-build-xcore-archive

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Provide a valid branch or commit hash"
        required: true

# Save the tag version in an environment variable
# The pretend version is used for the wheel as the
# tag version might be a branch name or commit hash
env:
  TAG_VERSION: ${{ github.event.inputs.version }}
  TOOLS_VERSION: 15.3.0
  TOOLS_LINK: https://www.xmos.ai/download/Tools-15---Linux-64(15_3_0).tgz
  
jobs:
  build-release-archive:
    name: Build release archive
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
          ref: ${{ env.TAG_VERSION }}
      - name: Build setup
        shell: bash
        run: |
          sudo apt-get -y -qq install libncurses5

          cd $GITHUB_WORKSPACE/third_party/lib_tflite_micro
          make patch

          wget -nv "${{ env.TOOLS_LINK }}?key=${{ secrets.TOOLS_KEY }}" -O tools.tgz
          tar xf tools.tgz
          cd XMOS/XTC/${{ env.TOOLS_VERSION }}
          source ./SetEnv

          cd $GITHUB_WORKSPACE/third_party/lib_tflite_micro
          mkdir -p build
          cd build
          cmake .. --toolchain=../lib_tflite_micro/submodules/xmos_cmake_toolchain/xs3a.cmake
          make create_zip -j4

      - uses: actions/upload-artifact@v2
        with:
          name: xcore-archive
          path: third_party/lib_tflite_micro/build/*.zip
